services:
  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=contacts
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d contacts"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./project-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_DIALECT=postgres
      - DATABASE_NAME=contacts
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_DIALECT_OPTIONS_SSL=false
      - JWT_SECRET=msipiPekjpJifGjTikyZRC6MAEslOM42
    depends_on:
      database:
        condition: 
          service_healthy
  
  frontend:
    build:
      context: ./project-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=backend/api
    depends_on:
      - backend

volumes:
  postgres_data:

  
